version: "3"

services:
  base: 
    image: local/kafka-base
    build: 
      context: ./image-kafka
      labels:
        cluster: kafka
      args:
        KAFKA_VERSION: 3.0.0
        SCALA_VERSION: 2.13
    command: ["echo", "...build base image for Kafka cluster..."]
  zookeeper-1:
    depends_on: 
      - base
    image: local/kafka-base
    expose:
      - 2181 # default port for zookeeper
    command: 
      - apache-kafka/bin/zookeeper-server-start.sh 
      - /app/zookeeper.properties
  kafka-1:
    depends_on:
      - base
      - zookeeper-1
    image: local/kafka-base
    environment: # KAFKA variables are processed by start_kafka.sh
      KAFKA_BROKER_ID: 1 
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
    ports:
      - 19092:19092
    entrypoint: 
      - /app/start_kafka.sh
  kafka-2:
    depends_on:
      - base
      - zookeeper-1
    image: local/kafka-base
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
    ports:
      - 29092:29092
    entrypoint: 
      - /app/start_kafka.sh

# TOOD: use Kraft mode to avoid starting up Zookeeper
