apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minikube-zk-pdb
  labels:
    app.kubernetes.io/name: minikube
    app.kubernetes.io/component: zookeeper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minikube
      app.kubernetes.io/component: zookeeper
  maxUnavailable: 2

# N.B. change apiVersion to work with minikube
# original: policy/v1beta1