apiVersion: "v1"
kind: "Service"
metadata:
  name: "minikube-kafka-headless"
  labels: &KafkaDeploymentLabels
    app.kubernetes.io/name: minikube
    app.kubernetes.io/component: kafka
spec:
  type: "ClusterIP"
  clusterIP: None
  ports:
    - name: "client"
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    - name: internal
      port: 9093
      protocol: TCP
      targetPort: kafka-internal
  selector: *KafkaDeploymentLabels
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "minikube-kafka-client"
  labels: &KafkaDeploymentLabels
    app.kubernetes.io/name: minikube
    app.kubernetes.io/component: kafka
spec:
  type: "ClusterIP"
  ports:
    - name: "client"
      port: 9092
      protocol: TCP
      targetPort: kafka-client
  selector: *KafkaDeploymentLabels