apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "minikube-kafka-pdb"
  labels: &KafkaDeploymentLabels
    app.kubernetes.io/name: minikube
    app.kubernetes.io/component: kafka
spec:
  selector:
    matchLabels: *KafkaDeploymentLabels
  maxUnavailable: 1
