apiVersion: v1
kind: Secret
metadata:
  name: minikube-kafka-secrets
  labels: &KafkaDeploymentLabels
    app.kubernetes.io/name: minikube
    app.kubernetes.io/component: kafka
type: Opaque
stringData:
  kafka_user: {{ .Values.kafka.kUser | quote }}
  kafka_password: {{ .Values.kafka.kPassword | quote }}
  kafka_server_jaas.conf: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username={{.Values.kafka.kUser | quote}}
        password={{.Values.kafka.kPassword | quote}}
        user_{{.Values.kafka.kUser}}={{.Values.kafka.kPassword | quote}};
      };
